# Environment & Configuration #
import os
from dotenv import load_dotenv

load_dotenv()


# LLM Generator Class #
class Generator:
    """
    Generates answers using high-speed Groq API (if GROQ_API_KEY is configured)
    or local Ollama models.
    """

    # Initialization & Client Setup #
    def __init__(self, model: str = None):
        self.groq_api_key = os.getenv("GROQ_API_KEY", "").strip()
        self.groq_model = os.getenv("GROQ_MODEL", "llama-3.3-70b-versatile")
        self.ollama_model = model or os.getenv("OLLAMA_MODEL", "qwen3:8b")

        if self.groq_api_key:
            try:
                from groq import Groq

                self.groq_client = Groq(api_key=self.groq_api_key)
                self.provider = "groq"
            except Exception as e:
                print(f"Warning: Failed to initialize Groq ({e}). Falling back to Ollama.")
                self.groq_client = None
                self.provider = "ollama"
        else:
            self.groq_client = None
            self.provider = "ollama"

    # Synchronous Answer Generation #
    def generate(
        self,
        question: str,
        retrieved_chunks: list[dict],
    ) -> str:

        # Validate Inputs #
        if not question.strip():
            raise ValueError("Question cannot be empty.")

        if not retrieved_chunks:
            return (
                "I could not find relevant information "
                "in the available company policies."
            )

        # Build Context from Retrieved Chunks #
        context_parts = []
        for chunk in retrieved_chunks:
            doc_name = chunk.get("document", "Policy Document")
            topic = chunk.get("topic", doc_name)
            section = chunk.get("section", "General")
            page_num = chunk.get("page", 1)

            context_parts.append(
                f"Document: {doc_name} (Page {page_num})\n"
                f"Policy Topic: {topic}\n"
                f"Section: {section}\n"
                f"Content: {chunk['text']}"
            )

        context = "\n\n---\n\n".join(context_parts)

        # System Prompt & Instructions #
        system_instruction = (
            "You are the official Employee Policy Assistant. "
            "Answer the question factually and directly in 1-2 clear sentences based strictly on the provided policy context. "
            "Do not include citations, section numbers, or document names in the prose. "
            "Do not explain your reasoning or include thinking steps. Output only the direct answer."
        )

        # User Prompt & Policy Context Assembly #
        user_content = f"""POLICY CONTEXT:
{context}

QUESTION:
{question}

DIRECT ANSWER:"""

        # Provider 1: High-Speed Groq Cloud LPU Inference #
        if self.provider == "groq" and self.groq_client:
            try:
                chat_completion = self.groq_client.chat.completions.create(
                    messages=[
                        {
                            "role": "system",
                            "content": system_instruction,
                        },
                        {
                            "role": "user",
                            "content": user_content,
                        },
                    ],
                    model=self.groq_model,
                    temperature=0.1,
                    max_completion_tokens=150,
                )
                return chat_completion.choices[0].message.content.strip()
            except Exception as e:
                print(f"Groq API error ({e}), falling back to Ollama.")

        # Provider 2: Local Ollama Model Inference #
        import ollama

        response = ollama.chat(
            model=self.ollama_model,
            messages=[
                {
                    "role": "system",
                    "content": system_instruction,
                },
                {
                    "role": "user",
                    "content": user_content,
                },
            ],
            options={
                "temperature": 0.1,
                "num_predict": 120,
                "top_p": 0.9,
            },
        )

        # Extract Response Text #
        if hasattr(response, "message"):
            msg = response.message
            content = getattr(msg, "content", "") or ""
            if not content.strip():
                content = getattr(msg, "thinking", "") or ""
        else:
            msg = response.get("message", {})
            content = msg.get("content", "") or msg.get("thinking", "")

        return content.strip() if content.strip() else "No answer generated by the model."

    # Live Real-Time Token Streaming Generator #
    def generate_stream(
        self,
        question: str,
        retrieved_chunks: list[dict],
    ):
        """
        Yields tokens one by one as they are generated by the LLM for live streaming.
        """
        if not question.strip():
            yield "Question cannot be empty."
            return

        if not retrieved_chunks:
            yield "I could not find relevant information in the available company policies."
            return

        # Format Context #
        context_parts = []
        for chunk in retrieved_chunks:
            doc_name = chunk.get("document", "Policy Document")
            topic = chunk.get("topic", doc_name)
            section = chunk.get("section", "General")
            page_num = chunk.get("page", 1)

            context_parts.append(
                f"Document: {doc_name} (Page {page_num})\n"
                f"Policy Topic: {topic}\n"
                f"Section: {section}\n"
                f"Content: {chunk['text']}"
            )

        context = "\n\n---\n\n".join(context_parts)

        # System Prompt #
        system_instruction = (
            "You are the official Employee Policy Assistant. "
            "Answer the question factually and directly in 1-2 clear sentences based strictly on the provided policy context. "
            "Do not include citations, section numbers, or document names in the prose. "
            "Do not explain your reasoning or include thinking steps. Output only the direct answer."
        )

        # User Prompt #
        user_content = f"""POLICY CONTEXT:
{context}

QUESTION:
{question}

DIRECT ANSWER:"""

        # Stream via Groq Cloud API with Natural ChatGPT Typing Cadence #
        if self.provider == "groq" and self.groq_client:
            try:
                import time

                stream_resp = self.groq_client.chat.completions.create(
                    messages=[
                        {"role": "system", "content": system_instruction},
                        {"role": "user", "content": user_content},
                    ],
                    model=self.groq_model,
                    temperature=0.1,
                    max_completion_tokens=150,
                    stream=True,
                )
                for chunk in stream_resp:
                    if chunk.choices and len(chunk.choices) > 0:
                        delta = chunk.choices[0].delta
                        token = getattr(delta, "content", "") or ""
                        if token:
                            yield token
                            time.sleep(0.018)  # Smooth natural word-by-word typing cadence
                return
            except Exception as e:
                print(f"Groq streaming error ({e}), falling back to Ollama streaming.")

        # Stream via Local Ollama #
        try:
            import ollama
            import time

            response_stream = ollama.chat(
                model=self.ollama_model,
                messages=[
                    {"role": "system", "content": system_instruction},
                    {"role": "user", "content": user_content},
                ],
                options={
                    "temperature": 0.1,
                    "num_predict": 120,
                    "top_p": 0.9,
                },
                stream=True,
            )

            for chunk in response_stream:
                if hasattr(chunk, "message"):
                    msg = chunk.message
                    token = getattr(msg, "content", "") or ""
                else:
                    msg = chunk.get("message", {})
                    token = msg.get("content", "")
                if token:
                    yield token
                    time.sleep(0.018)
        except Exception as err:
            yield f"Inference error: {err}"