import os
from dotenv import load_dotenv

load_dotenv()


class Generator:
    """
    Generates answers using high-speed Groq API (if GROQ_API_KEY is configured)
    or local Ollama models.
    """

    def __init__(self, model: str = None):
        self.groq_api_key = os.getenv("GROQ_API_KEY", "").strip()
        self.groq_model = os.getenv("GROQ_MODEL", "llama-3.3-70b-versatile")
        self.ollama_model = model or os.getenv("OLLAMA_MODEL", "qwen3:8b")

        if self.groq_api_key:
            try:
                from groq import Groq

                self.groq_client = Groq(api_key=self.groq_api_key)
                self.provider = "groq"
            except Exception as e:
                print(f"Warning: Failed to initialize Groq ({e}). Falling back to Ollama.")
                self.groq_client = None
                self.provider = "ollama"
        else:
            self.groq_client = None
            self.provider = "ollama"

    def generate(
        self,
        question: str,
        retrieved_chunks: list[dict],
    ) -> str:

        if not question.strip():
            raise ValueError("Question cannot be empty.")

        if not retrieved_chunks:
            return (
                "I could not find relevant information "
                "in the available company policies."
            )

        context_parts = []

        for chunk in retrieved_chunks:
            doc_name = chunk.get("document", "Policy Document")
            topic = chunk.get("topic", doc_name)
            section = chunk.get("section", "General")
            page_num = chunk.get("page", 1)

            context_parts.append(
                f"Document: {doc_name} (Page {page_num})\n"
                f"Policy Topic: {topic}\n"
                f"Section: {section}\n"
                f"Content: {chunk['text']}"
            )

        context = "\n\n---\n\n".join(context_parts)

        system_instruction = (
            "You are the official Employee Policy Assistant. "
            "Answer the question factually and directly in 1-2 clear sentences based strictly on the provided policy context. "
            "Do not include citations, section numbers, or document names in the prose. "
            "Do not explain your reasoning or include thinking steps. Output only the direct answer."
        )

        user_content = f"""POLICY CONTEXT:
{context}

QUESTION:
{question}

DIRECT ANSWER:"""

        # ---------------------------------------------
        # High-Speed Groq Inference (~0.3s)
        # ---------------------------------------------
        if self.provider == "groq" and self.groq_client:
            try:
                chat_completion = self.groq_client.chat.completions.create(
                    messages=[
                        {
                            "role": "system",
                            "content": system_instruction,
                        },
                        {
                            "role": "user",
                            "content": user_content,
                        },
                    ],
                    model=self.groq_model,
                    temperature=0.1,
                    max_completion_tokens=150,
                )
                return chat_completion.choices[0].message.content.strip()
            except Exception as e:
                print(f"Groq API error ({e}), falling back to Ollama.")

        # ---------------------------------------------
        # Local Ollama Inference
        # ---------------------------------------------
        import ollama

        response = ollama.chat(
            model=self.ollama_model,
            messages=[
                {
                    "role": "system",
                    "content": system_instruction,
                },
                {
                    "role": "user",
                    "content": user_content,
                },
            ],
            options={
                "temperature": 0.1,
                "num_predict": 120,
                "top_p": 0.9,
            },
        )

        # Extract answer safely from ChatResponse model or dictionary
        if hasattr(response, "message"):
            msg = response.message
            content = getattr(msg, "content", "") or ""
            if not content.strip():
                content = getattr(msg, "thinking", "") or ""
        else:
            msg = response.get("message", {})
            content = msg.get("content", "") or msg.get("thinking", "")

        return content.strip() if content.strip() else "No answer generated by the model."